version: '3.9'
services:
  apirest:
    build: .
    ports:
      - "3001:3001"
    links:
      - dbmongo
  dbmongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=secret
